1.1_menuUTILIZADORES.h
NR
Referenced by ler_u, gravar_u, inserir_u, mostrar_u, UTILIZADORES, ler_l, gravar_l, inserir_l, mostrar_l, LIVROS, ler_requisicao, gravar_requisicao, mostrar_requisicao, inserir, REQUISICOES.
void ler_u(utilizador *x)
References NR, utilizador::estado.
Referenced by UTILIZADORES, inserir.
void gravar_u(utilizador *x)
References NR.
Referenced by UTILIZADORES.
void inserir_u(utilizador *x)
References limpa_ecra, NR, utilizador::id_uti, utilizador::estado.
Referenced by UTILIZADORES.
int editar_u(utilizador *x)
References utilizador::estado.
Referenced by UTILIZADORES.
int eliminar_u(utilizador *x)
References limpa_ecra, utilizador::estado.
Referenced by UTILIZADORES.
void mostrar_u(utilizador *x)
References NR.
Referenced by UTILIZADORES.
void UTILIZADORES(void)
References NR, ler_u, inserir_u, eliminar_u, editar_u, mostrar_u, gravar_u, limpa_ecra.
Referenced by MENU_PRINCIPAL.