addbook.c
RETURNTIME
char catagories[][15][][15]
Referenced by addbooks, getdata.
FILE* fp
Referenced by addbooks, checkid.
FILE * ft
FILE * fs
int s
Referenced by addbooks, getdata.
char findbook
struct books a
Referenced by addbooks, getdata, checkid, issuerecord.
int main()
References addbooks.
void addbooks(void)
References s, fp, getdata, a, books::cat, catagories.
Referenced by main, getdata.
int getdata()
References t, catagories, s, checkid, addbooks, a, books::id, books::name, books::Author, books::quantity, books::Price, books::rackno.
Referenced by addbooks.
int checkid(int t)
References fp, a, books::id.
Referenced by getdata.
int t(void)
Referenced by MENU_PRINCIPAL, getdata.
void issuerecord()
References a, books::stname, books::issued, meroDate::dd, meroDate::mm, meroDate::yy, books::duedate.