deletebooks.c
RETURNTIME
char catagories[][15][][15]
Referenced by getdata.
FILE* fp
Referenced by deletebooks, checkid.
FILE * ft
Referenced by deletebooks.
FILE * fs
int s
Referenced by getdata.
char findbook
Referenced by deletebooks.
struct books a
Referenced by deletebooks, returnfunc, getdata, checkid.
void delay(unsigned int mseconds)
int main()
References deletebooks.
void deletebooks()
References fp, a, books::id, books::name, books::rackno, findbook, ft.
Referenced by main, returnfunc, getdata.
void returnfunc(void)
References a, deletebooks.
int getdata()
References t, catagories, s, checkid, deletebooks, a, books::id, books::name, books::Author, books::quantity, books::Price, books::rackno.
int checkid(int t)
References fp, a, books::id.
Referenced by getdata.
int t(void)
Referenced by getdata.