editbooks.c
RETURNTIME
char catagories[][15][][15]
Referenced by getdata.
FILE* fp
Referenced by viewbooks, editbooks, checkid.
FILE * ft
FILE * fs
int s
Referenced by getdata.
char findbook
struct books a
Referenced by viewbooks, editbooks, returnfunc, getdata, checkid, issuerecord.
void delay(unsigned int mseconds)
int main()
References viewbooks.
void viewbooks(void)
References fp, a, books::cat, books::id, books::name, books::Author, books::quantity, books::Price, books::rackno, returnfunc.
Referenced by main, returnfunc, getdata.
void editbooks(void)
References fp, a, checkid, books::id, books::name, books::Author, books::quantity, books::Price, books::rackno, returnfunc.
void returnfunc(void)
References a, viewbooks.
Referenced by viewbooks, editbooks.
int getdata()
References t, catagories, s, checkid, viewbooks, a, books::id, books::name, books::Author, books::quantity, books::Price, books::rackno.
int checkid(int t)
References fp, a, books::id.
Referenced by editbooks, getdata.
int t(void)
Referenced by getdata.
void issuerecord()
References a, books::stname, books::issued, meroDate::dd, meroDate::mm, meroDate::yy, books::duedate.