requisicoes.c
RETURNTIME
Referenced by issuebooks.
char catagories[][15][][15]
Referenced by getdata.
FILE* fp
Referenced by issuebooks, checkid.
FILE * ft
FILE * fs
Referenced by issuebooks.
int s
Referenced by getdata.
char findbook
Referenced by issuebooks.
struct books a
Referenced by issuebooks, returnfunc, getdata, checkid, issuerecord.
void delay(unsigned int mseconds)
int main()
References issuebooks.
void issuebooks(void)
References t, fp, fs, checkid, a, books::quantity, books::name, books::stname, books::issued, meroDate::dd, meroDate::mm, meroDate::yy, books::id, books::duedate, RETURNTIME, books::cat, returnfunc, issuerecord, findbook.
Referenced by main, returnfunc, getdata.
void returnfunc(void)
References a, issuebooks.
Referenced by issuebooks.
int getdata()
References t, catagories, s, checkid, issuebooks, a, books::id, books::name, books::Author, books::quantity, books::Price, books::rackno.
int checkid(int t)
References fp, a, books::id.
Referenced by issuebooks, getdata.
int t(void)
Referenced by issuebooks, getdata.
void issuerecord()
References a, books::stname, books::issued, meroDate::dd, meroDate::mm, meroDate::yy, books::duedate.
Referenced by issuebooks.