0.1_menu_principal.c
RETURNTIME
void limpa_ecra()
Referenced by MENU_PRINCIPAL, inserir_u, eliminar_u, UTILIZADORES, inserir_l, eliminar_l, mostrar_l, LIVROS, inserir, REQUISICOES.
void MENU_PRINCIPAL()
References limpa_ecra, t, UTILIZADORES, LIVROS, REQUISICOES.
Referenced by main.
int main()
References MENU_PRINCIPAL.