1.2_menuLIVROS.h
M
void ler_l(livro *y)
References NR, livro::estado.
Referenced by LIVROS, inserir.
void gravar_l(livro *y)
References NR.
Referenced by LIVROS, REQUISICOES.
void inserir_l(livro *y)
References limpa_ecra, NR, livro::id_liv, livro::estado.
Referenced by LIVROS.
int editar_l(livro *y)
References livro::estado.
Referenced by LIVROS.
int eliminar_l(livro *y)
References limpa_ecra, livro::estado.
Referenced by LIVROS.
void mostrar_l(livro *y)
References limpa_ecra, NR.
Referenced by LIVROS.
void LIVROS(void)
References liv, NR, ler_l, limpa_ecra, inserir_l, eliminar_l, editar_l, mostrar_l, gravar_l.
Referenced by MENU_PRINCIPAL.