1.3_menuREQUISICOES.h
M
void ler_requisicao(requisicao *z)
References NR, requisicao::estado.
Referenced by REQUISICOES.
void gravar_requisicao(requisicao *z)
References NR.
Referenced by REQUISICOES.
void mostrar_requisicao(requisicao *z)
References NR.
Referenced by REQUISICOES.
void inserir(requisicao *z, livro *y, utilizador *x)
References limpa_ecra, NR, requisicao::id_requisicao, ler_l, livro::estado, requisicao::id_liv_r, ler_u, requisicao::id_uti_r, requisicao::estado.
Referenced by REQUISICOES.
int concluir(requisicao *z)
References requisicao::estado.
Referenced by REQUISICOES.
void REQUISICOES()
References NR, ler_requisicao, limpa_ecra, inserir, concluir, mostrar_requisicao, gravar_requisicao, gravar_l.
Referenced by MENU_PRINCIPAL.