.TH "source/1.3_menuREQUISICOES.h" 3 "Thu Dec 11 2014" "Version 1" "Biblioteca Universal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/1.3_menuREQUISICOES.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBrequisicao\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBM\fP   100"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBler_requisicao\fP (\fBrequisicao\fP *z)"
.br
.ti -1c
.RI "void \fBgravar_requisicao\fP (\fBrequisicao\fP *z)"
.br
.ti -1c
.RI "void \fBmostrar_requisicao\fP (\fBrequisicao\fP *z)"
.br
.ti -1c
.RI "void \fBinserir\fP (\fBrequisicao\fP *z, \fBlivro\fP *y, \fButilizador\fP *x)"
.br
.ti -1c
.RI "int \fBconcluir\fP (\fBrequisicao\fP *z)"
.br
.ti -1c
.RI "void \fBREQUISICOES\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define M   100"

.SH "Function Documentation"
.PP 
.SS "int concluir (\fBrequisicao\fP *z)"

.SS "void gravar_requisicao (\fBrequisicao\fP *z)"

.SS "void inserir (\fBrequisicao\fP *z, \fBlivro\fP *y, \fButilizador\fP *x)"

.SS "void ler_requisicao (\fBrequisicao\fP *z)"
'rt' --> r- ler, t-ficheiro de texto 
.SS "void mostrar_requisicao (\fBrequisicao\fP *z)"

.SS "void REQUISICOES ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Biblioteca Universal from the source code\&.
