.TH "books" 3 "Thu Dec 11 2014" "Version 1" "Biblioteca Universal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
books \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "char \fBstname\fP [20]"
.br
.ti -1c
.RI "char \fBname\fP [20]"
.br
.ti -1c
.RI "char \fBAuthor\fP [20]"
.br
.ti -1c
.RI "int \fBquantity\fP"
.br
.ti -1c
.RI "float \fBPrice\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "int \fBrackno\fP"
.br
.ti -1c
.RI "char * \fBcat\fP"
.br
.ti -1c
.RI "struct \fBmeroDate\fP \fBissued\fP"
.br
.ti -1c
.RI "struct \fBmeroDate\fP \fBduedate\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char Author"

.SS "char * cat"

.SS "int count"

.SS "struct \fBmeroDate\fP duedate"

.SS "int id"

.SS "struct \fBmeroDate\fP issued"

.SS "char name"

.SS "float Price"

.SS "int quantity"

.SS "int rackno"

.SS "char stname"


.SH "Author"
.PP 
Generated automatically by Doxygen for Biblioteca Universal from the source code\&.
