.TH "source/inicio-adicionarlivro-exemplo.c" 3 "Thu Dec 11 2014" "Version 1" "Biblioteca Universal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/inicio-adicionarlivro-exemplo.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "adicionar \fBlivro\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "adicionar \fBlivro\fP ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Biblioteca Universal from the source code\&.
