.TH "LIVROS" 3 "Thu Dec 11 2014" "Version 1" "Biblioteca Universal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LIVROS \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBtit\fP [20]"
.br
.ti -1c
.RI "char \fBaut\fP [16]"
.br
.ti -1c
.RI "char \fBed\fP [10]"
.br
.ti -1c
.RI "char \fBgen\fP [10]"
.br
.ti -1c
.RI "int \fBidl\fP [4]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char aut[16]"

.SS "char ed[10]"

.SS "char gen[10]"

.SS "int idl[4]"

.SS "char tit[20]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Biblioteca Universal from the source code\&.
