.TH "meroDate" 3 "Thu Dec 11 2014" "Version 1" "Biblioteca Universal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
meroDate \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBmm\fP"
.br
.ti -1c
.RI "int \fBdd\fP"
.br
.ti -1c
.RI "int \fByy\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int dd"

.SS "int mm"

.SS "int yy"


.SH "Author"
.PP 
Generated automatically by Doxygen for Biblioteca Universal from the source code\&.
