.TH "source/0.1_menu_principal.c" 3 "Thu Dec 11 2014" "Version 1" "Biblioteca Universal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/0.1_menu_principal.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <conio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include <dos\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include '1\&.1_menuUTILIZADORES\&.h'\fP
.br
\fC#include '1\&.2_menuLIVROS\&.h'\fP
.br
\fC#include '1\&.3_menuREQUISICOES\&.h'\fP
.br
\fC#include 'relogio\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRETURNTIME\fP   15"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBlimpa_ecra\fP ()"
.br
.ti -1c
.RI "void \fBMENU_PRINCIPAL\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RETURNTIME   15"

.SH "Function Documentation"
.PP 
.SS "void limpa_ecra ()"
Função utilizada para limpar o ecrã\&. Assim, sempre que necessário, basta chamar \fBlimpa_ecra()\fP 
.SS "int main ()"

.SS "void MENU_PRINCIPAL ()"
Estrutura global do programa BIBLIOTECATIC 
.SH "Author"
.PP 
Generated automatically by Doxygen for Biblioteca Universal from the source code\&.
