.TH "source/1.1_menuUTILIZADORES.h" 3 "Thu Dec 11 2014" "Version 1" "Biblioteca Universal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/1.1_menuUTILIZADORES.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fButilizador\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNR\fP   100"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBler_u\fP (\fButilizador\fP *x)"
.br
.ti -1c
.RI "void \fBgravar_u\fP (\fButilizador\fP *x)"
.br
.ti -1c
.RI "void \fBinserir_u\fP (\fButilizador\fP *x)"
.br
.ti -1c
.RI "int \fBeditar_u\fP (\fButilizador\fP *x)"
.br
.ti -1c
.RI "int \fBeliminar_u\fP (\fButilizador\fP *x)"
.br
.ti -1c
.RI "void \fBmostrar_u\fP (\fButilizador\fP *x)"
.br
.ti -1c
.RI "void \fBUTILIZADORES\fP (void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NR   100"

.SH "Function Documentation"
.PP 
.SS "int editar_u (\fButilizador\fP *x)"

.SS "int eliminar_u (\fButilizador\fP *x)"

.SS "void gravar_u (\fButilizador\fP *x)"

.SS "void inserir_u (\fButilizador\fP *x)"

.SS "void ler_u (\fButilizador\fP *x)"

.SS "void mostrar_u (\fButilizador\fP *x)"

.SS "void \fBUTILIZADORES\fP (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Biblioteca Universal from the source code\&.
