.TH "source/1.4_menuGESTAO.h" 3 "Thu Dec 11 2014" "Version 1" "Biblioteca Universal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/1.4_menuGESTAO.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBGESTAO\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void GESTAO ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Biblioteca Universal from the source code\&.
