.TH "source Directory Reference" 3 "Thu Dec 11 2014" "Version 1" "Biblioteca Universal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB0\&.1_menu_principal\&.c\fP"
.br
.ti -1c
.RI "file \fB1\&.1_menuUTILIZADORES\&.h\fP"
.br
.ti -1c
.RI "file \fB1\&.2_menuLIVROS\&.h\fP"
.br
.ti -1c
.RI "file \fB1\&.3_menuREQUISICOES\&.h\fP"
.br
.ti -1c
.RI "file \fB1\&.4_menuGESTAO\&.h\fP"
.br
.ti -1c
.RI "file \fBinicio-adicionarlivro-exemplo\&.c\fP"
.br
.ti -1c
.RI "file \fBinicio-estruturas\&.c\fP"
.br
.ti -1c
.RI "file \fBProjeto1_private\&.h\fP"
.br
.ti -1c
.RI "file \fBrelogio\&.h\fP"
.br
.in -1c
