.TH "source/inicio-estruturas.c" 3 "Thu Dec 11 2014" "Version 1" "Biblioteca Universal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/inicio-estruturas.c \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBLIVROS\fP"
.br
.ti -1c
.RI "struct \fBUTILIZADORES\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct LIVRO \fBliv\fP"
.br
.ti -1c
.RI "struct \fBUTILIZADORES\fP \fBut\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "struct LIVRO liv"

.SS "struct \fBUTILIZADORES\fP ut"

.SH "Author"
.PP 
Generated automatically by Doxygen for Biblioteca Universal from the source code\&.
