.TH "livro" 3 "Thu Dec 11 2014" "Version 1" "Biblioteca Universal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
livro \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <1\&.2_menuLIVROS\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long int \fBid_liv\fP"
.br
.ti -1c
.RI "char \fBtitulo\fP [60]"
.br
.RI "\fIID do Livro\&. \fP"
.ti -1c
.RI "char \fBautor\fP [60]"
.br
.RI "\fITitulo\&. \fP"
.ti -1c
.RI "char \fBgen\fP [10]"
.br
.RI "\fIAutor\&. \fP"
.ti -1c
.RI "int \fBestado\fP"
.br
.RI "\fIGenero\&. \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "char autor[60]"

.PP
Titulo\&. 
.SS "int estado"

.PP
Genero\&. 
.SS "char gen[10]"

.PP
Autor\&. 
.SS "long int id_liv"

.SS "char titulo[60]"

.PP
ID do Livro\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Biblioteca Universal from the source code\&.
