.TH "requisicao" 3 "Thu Dec 11 2014" "Version 1" "Biblioteca Universal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
requisicao \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <1\&.3_menuREQUISICOES\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long int \fBid_uti_r\fP"
.br
.ti -1c
.RI "long int \fBid_liv_r\fP"
.br
.RI "\fIID de utilizador, ID de Livro e ID de Requisicao\&. \fP"
.ti -1c
.RI "long int \fBid_requisicao\fP"
.br
.ti -1c
.RI "char \fBtitulo_r\fP [60]"
.br
.ti -1c
.RI "char \fBnome_r\fP [60]"
.br
.RI "\fITitulo do livro\&. \fP"
.ti -1c
.RI "int \fBestado\fP"
.br
.RI "\fINome do utilizador\&. \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "int estado"

.PP
Nome do utilizador\&. 
.SS "long int id_liv_r"

.PP
ID de utilizador, ID de Livro e ID de Requisicao\&. 
.SS "long int id_requisicao"

.SS "long int id_uti_r"

.SS "char nome_r[60]"

.PP
Titulo do livro\&. 
.SS "char titulo_r[60]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Biblioteca Universal from the source code\&.
