.TH "utilizador" 3 "Thu Dec 11 2014" "Version 1" "Biblioteca Universal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utilizador \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <1\&.1_menuUTILIZADORES\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long int \fBid_uti\fP"
.br
.ti -1c
.RI "char \fBnome_uti\fP [60]"
.br
.ti -1c
.RI "char \fBmail\fP [60]"
.br
.ti -1c
.RI "char \fBdn\fP [10]"
.br
.ti -1c
.RI "int \fBtele\fP"
.br
.ti -1c
.RI "int \fBestado\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char dn[10]"

.SS "int estado"

.SS "long int id_uti"

.SS "char mail[60]"

.SS "char nome_uti[60]"

.SS "int tele"


.SH "Author"
.PP 
Generated automatically by Doxygen for Biblioteca Universal from the source code\&.
