.TH "UTILIZADORES" 3 "Thu Dec 11 2014" "Version 1" "Biblioteca Universal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UTILIZADORES \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBnome\fP [20]"
.br
.ti -1c
.RI "int \fBdn\fP [8]"
.br
.ti -1c
.RI "int \fBtele\fP [9]"
.br
.ti -1c
.RI "char \fBmail\fP [20]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int dn[8]"

.SS "char mail[20]"

.SS "char nome[20]"

.SS "int tele[9]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Biblioteca Universal from the source code\&.
